version: 2.1
jobs:
  client:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install Client Dependencies
          command: cd client && npm install
      - run:
          name: Build and test client
          command: cd client && npm run build && npm run test
  server:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install Server Dependencies
          command: cd server && npm install
      - run:
          name: Run server
          command: cd server && npm start
workflows:
  version: 2.1
  client_and_server:
    jobs:
      - client
      - server
