jobs:
  client:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: test
          command: npm test
  server:
    docker:
      - image: circleci/node:10.16.3
      - image: mongo:4.2.0
    steps:
      - checkout
      - run:
          name: start
          command: npm start
workflows:
  version: 2
  client_and_server:
    jobs:
      - client
      - server
